import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Menu, X, Languages, LogIn, UserRound } from 'lucide-react';
import { onAuthStateChanged, User } from 'firebase/auth';
import { auth, firebaseConfigured } from './lib/firebase';
import { words, Lang } from './lib/i18n';
import Home from './pages/Home'; import Apply from './pages/Apply'; import Contact from './pages/Contact'; import Portal from './pages/Portal'; import PhoneLogin from './components/PhoneLogin';
import './styles.css';
export default function App(){const [lang,setLang]=useState<Lang>('en');const [user,setUser]=useState<User|null>(auth.currentUser);const [menu,setMenu]=useState(false);const location=useLocation();const nav=useNavigate();const t=words[lang];
 useEffect(()=>onAuthStateChanged(auth,setUser),[]);useEffect(()=>setMenu(false),[location.pathname]);
 const links=[['/',t.home],['/loans',t.loans],['/about',t.about],['/apply',t.apply],['/contact',t.contact]];
 return <div className="app-shell"><header className="topbar"><Link className="brand" to="/"><span className="brand-mark">U<span>↗</span></span><span>Udaan <b>Credit</b><small>FINANCIAL SERVICES</small></span></Link><button className="mobile-menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'nav open':'nav'}>{links.map(([to,label])=><NavLink key={to} to={to} end={to==='/'}>{label}</NavLink>)}</nav><div className="top-actions"><button className="language" onClick={()=>setLang(lang==='en'?'hi':'en')} aria-label="Switch language"><Languages size={17}/>{lang==='en'?'हिन्दी':'English'}</button>{user?<button className="account-btn" onClick={()=>nav('/dashboard')}><UserRound size={17}/>Account</button>:<button className="login-btn" onClick={()=>nav('/login')}><LogIn size={17}/>{t.login}</button>}</div></header>
 {!firebaseConfigured&&<div className="config-warning">{t.notConfigured}</div>}
 <main><Routes><Route path="/" element={<Home t={t} lang={lang}/>}/><Route path="/apply" element={<Apply/>}/><Route path="/contact" element={<Contact/>}/><Route path="/loans" element={<InfoPage title="Loan products" body="Loan categories and product terms will appear here when configured and verified by an authorized administrator. No rates or lender partnerships are assumed."/>}/><Route path="/about" element={<InfoPage title="About Udaan Credit" body="Udaan Credit aims to provide clear loan enquiry and application-tracking workflows. Lender approval, rates and disbursement are determined by the authorized lender."/>}/><Route path="/referral" element={<InfoPage title="Referral partner program" body="Partner registration, terms acceptance, identity verification and commission eligibility must be configured before referrals can be accepted. Contact hr.ucmf@gmail.com for program information."/>}/><Route path="/login" element={user?<Portal/>:<div className="form-page"><PhoneLogin onDone={()=>nav((location.state as {from?:string}|null)?.from||'/dashboard',{replace:true})}/></div>}/><Route path="/dashboard" element={user?<Portal/>:<div className="form-page"><PhoneLogin onDone={()=>nav('/dashboard',{replace:true})}/></div>}/><Route path="*" element={<InfoPage title="Page not found" body="The page you requested does not exist."/>}/></Routes></main>
 <footer className="footer"><div className="footer-top"><div className="brand footer-brand"><span className="brand-mark">U<span>↗</span></span><span>Udaan <b>Credit</b><small>FINANCIAL SERVICES</small></span></div><p>Clear information. Responsible assistance.</p><div className="footer-contact"><a href="mailto:hr.ucmf@gmail.com">hr.ucmf@gmail.com</a><a href="tel:+918741012464">+91 87410 12464</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Udaan Credit</span><span>Loan approval is subject to lender verification and eligibility.</span><span>{t.privacy} · {t.terms} · {t.disclaimer}</span></div></footer></div>
}
function InfoPage({title,body}:{title:string;body:string}){return <section className="form-page"><div className="panel"><span className="eyebrow">UDAAN CREDIT</span><h1>{title}</h1><p>{body}</p><p className="muted small">This section is a safe content placeholder until the relevant verified records and admin workflow are implemented.</p></div></section>}
