import { ArrowUpRight, ShieldCheck, ClipboardCheck, Headset, CircleHelp } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Lang } from '../lib/i18n';
export default function Home({t,lang}:{t:Record<string,string>;lang:Lang}) { return <>
<section className="hero"><div className="hero-copy"><span className="eyebrow">UDAAN CREDIT · TRANSPARENT LOAN ASSISTANCE</span><h1>{t.hero}</h1><p>{t.subtitle}</p><div className="hero-actions"><Link className="btn primary" to="/apply">{t.applyNow}<ArrowUpRight size={18}/></Link><Link className="btn secondary" to="/referral">{t.referral}</Link></div><p className="disclaimer">Loan applications are subject to lender eligibility, verification and approval. Udaan Credit does not guarantee approval.</p></div><div className="hero-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-symbol">U<span>↗</span></div><div className="float-card"><ShieldCheck/><div><b>Clear information</b><small>Know what is verified</small></div></div></div></section>
<section className="section"><div className="section-heading"><span className="eyebrow">WHY UDAAN CREDIT</span><h2>{t.benefits}</h2></div><div className="feature-grid"><article className="feature"><ShieldCheck/><h3>Transparency first</h3><p>Review published terms and disclosures before sharing your details.</p></article><article className="feature"><ClipboardCheck/><h3>Track your request</h3><p>View your application status after secure customer sign-in.</p></article><article className="feature"><Headset/><h3>Support when needed</h3><p>Contact our team for application questions and complaint support.</p></article></div></section>
<section className="section soft"><div className="section-heading"><span className="eyebrow">THE PROCESS</span><h2>{t.process}</h2></div><div className="steps"><div><b>01</b><h3>Explore</h3><p>Compare available products and eligibility criteria.</p></div><div><b>02</b><h3>Apply</h3><p>Submit an enquiry with appropriate consent.</p></div><div><b>03</b><h3>Track</h3><p>Follow updates as verified information becomes available.</p></div></div></section>
<section className="section faq"><div><span className="eyebrow">NEED CLARITY?</span><h2>{t.faq}</h2></div><div><details><summary><CircleHelp size={18}/> Does applying guarantee a loan?</summary><p>No. Only the relevant lender can assess and approve a loan application.</p></details><details><summary><CircleHelp size={18}/> Are rates and balances guaranteed here?</summary><p>Only published, authorized terms and verified account records will be displayed. Estimates are labelled clearly.</p></details><details><summary><CircleHelp size={18}/> How do I track an application?</summary><p>Sign in with your mobile number and OTP to view applications linked to your account.</p></details></div></section>
<section className="contact-band"><div><h2>Have a question?</h2><p>Reach our support team for help with your enquiry.</p></div><Link className="btn secondary" to="/contact">Contact us <ArrowUpRight size={18}/></Link></section>
</> }
